name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - notebook=6.4.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.2.0
  - pyarrow=9.0.0
  - protobuf=3.20.1
  - ipywidgets=8.0.1
  - pip:
      - wandb==0.10.31