name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - mlflow=1.14.1
  - ipython=7.33.0
  - notebook=6.4.12
  - cookiecutter=1.7.2
  - hydra-core=1.1
  - matplotlib=3.3.4
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
