name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.18.0
  - scikit-learn=0.24.1
  - protobuf=3.20.1
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
